# workflow name in UI
name: Post Push Tests

# trigger workflow only on push to main branch
on:
  push:
    branches: [main]

jobs:
  test: # job name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit
