version: "3"
services:
  redis-server:
    image: "redis"
  node-app:
    restart: always
    build: .
    ports:
      - "80:3000"
#
# Restart policies:
#   "no" (default - must be quoted otherwise it is understood as a boolean)
#   always
#   on-failure
#   unless-stopped
